service: godiet
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  httpApi:
    cors:
      allowedOrigins:
        - 'https://godiet.com.br'
        - 'http://localhost:5173'
      allowedHeaders:
        - '*'
      allowedMethods:
        - PUT
        - GET
        - DELETE
        - POST
        - OPTIONS

custom:
  secrets: ${file(.env.prod)}
  esbuild:
    target: node20
    # format: esm
    minify: true
    # outputFileExtension: .mjs
    # banner:
    #   js: 'import { createRequire } from "module";const require = createRequire(import.meta.url)'

functions:
  authSignin:
    handler: src/server/functions/auth/signin.handler
    events:
      - httpApi:
          path: /auth/signin
          method: POST

  authSignup:
    handler: src/server/functions/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST

  createPatient:
    handler: src/server/functions/patient/create.handler
    events:
      - httpApi:
          path: /patient
          method: POST
  findAllPatients:
    handler: src/server/functions/patient/findAll.handler
    events:
      - httpApi:
          path: /patient
          method: GET
  findByPatientId:
    handler: src/server/functions/patient/findByPatientId.handler
    events:
      - httpApi:
          path: /patient/{patientId}
          method: GET
  updatePatient:
    handler: src/server/functions/patient/update.handler
    events:
      - httpApi:
          path: /patient/{patientId}
          method: PUT
  deletePatient:
    handler: src/server/functions/patient/delete.handler
    events:
      - httpApi:
          path: /patient/{patientId}
          method: DELETE

  findAllFavoriteMeal:
    handler: src/server/functions/favoriteMeal/findAll.handler
    events:
      - httpApi:
          path: /favoriteMeal
          method: GET
  deleteFavoriteMeal:
    handler: src/server/functions/favoriteMeal/delete.handler
    events:
      - httpApi:
          path: /favoriteMeal/{favoriteMealId}
          method: DELETE
  createFavoriteMeal:
    handler: src/server/functions/favoriteMeal/create.handler
    events:
      - httpApi:
          path: /favoriteMeal
          method: POST

  findAllFoods:
    handler: src/server/functions/food/findAll.handler
    events:
      - httpApi:
          path: /foods
          method: GET

  findAllCategoryName:
    handler: src/server/functions/categoryName/findAll.handler
    events:
      - httpApi:
          path: /categoryName
          method: GET

  createPlanningMeal:
    handler: src/server/functions/planningMeal/create.handler
    events:
      - httpApi:
          path: /planningMeal/{patientId}
          method: POST
  deletePlanningMeal:
    handler: src/server/functions/planningMeal/delete.handler
    events:
      - httpApi:
          path: /planningMeal/{patientId}
          method: DELETE
  findAllPlanning:
    handler: src/server/functions/planningMeal/findAll.handler
    events:
      - httpApi:
          path: /planningMeal/{patientId}
          method: GET

  createObservationTemplate:
    handler: src/server/functions/observationTemplate/create.handler
    events:
      - httpApi:
          path: /observation-template
          method: POST
  deleteObservationTemplate:
    handler: src/server/functions/observationTemplate/delete.handler
    events:
      - httpApi:
          path: /observation-template/{id}
          method: DELETE
  findAllObservationTemplate:
    handler: src/server/functions/observationTemplate/findAll.handler
    events:
      - httpApi:
          path: /observation-template
          method: GET
  updateObservationTemplate:
    handler: src/server/functions/observationTemplate/update.handler
    events:
      - httpApi:
          path: /observation-template
          method: PUT

  createAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/create.handler
    events:
      - httpApi:
          path: /anamnesisTemplate
          method: POST
  findAllAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/findAll.handler
    events:
      - httpApi:
          path: /anamnesisTemplate
          method: GET
  deleteAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/delete.handler
    events:
      - httpApi:
          path: /anamnesisTemplate/{anamnesisId}
          method: DELETE

  createAnamnesis:
    handler: src/server/functions/anamnesis/create.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: POST

  findAllAnamnesis:
    handler: src/server/functions/anamnesis/findAll.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: GET

  updateAnamnesis:
    handler: src/server/functions/anamnesis/update.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: PUT

  deleteAnamnesis:
    handler: src/server/functions/anamnesis/delete.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}/{anamnesisId}
          method: DELETE

  userMe:
    handler: src/server/functions/user/me.handler
    events:
      - httpApi:
          path: /user/me
          method: GET
