service: godiet
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512

custom:
  esbuild:
    target: node20
    # format: esm
    minify: true
    # outputFileExtension: .mjs
    # banner:
    #   js: 'import { createRequire } from "module";const require = createRequire(import.meta.url)'

functions:
  getUserById:
    handler: src/server/functions/getUserById.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
  authSignin:
    handler: src/server/functions/auth/signin.handler
    events:
      - httpApi:
          path: /auth/signin
          method: POST
  authSignup:
    handler: src/server/functions/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST
  createPatient:
    handler: src/server/functions/patient/create.handler
    events:
      - httpApi:
          path: /patient
          method: POST
  findAllPatients:
    handler: src/server/functions/patient/findAll.handler
    events:
      - httpApi:
          path: /patient
          method: GET
  userMe:
    handler: src/server/functions/user/me.handler
    events:
      - httpApi:
          path: /user/me
          method: GET
