service: godiet
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512

custom:
  secrets: ${file(.env.prod)}
  esbuild:
    target: node20
    # format: esm
    minify: true
    # outputFileExtension: .mjs
    # banner:
    #   js: 'import { createRequire } from "module";const require = createRequire(import.meta.url)'

functions:
  getUserById:
    handler: src/server/functions/getUserById.handler
    events:
      - httpApi:
          path: /users/{userId}
          method: GET
          cors: true
  authSignin:
    handler: src/server/functions/auth/signin.handler
    events:
      - httpApi:
          path: /auth/signin
          method: POST
          cors: true
  authSignup:
    handler: src/server/functions/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST
          cors: true

  createPatient:
    handler: src/server/functions/patient/create.handler
    events:
      - httpApi:
          path: /patient
          method: POST
          cors: true
  findAllPatients:
    handler: src/server/functions/patient/findAll.handler
    events:
      - httpApi:
          path: /patient
          method: GET
          cors: true
  findByPatientId:
    handler: src/server/functions/patient/findByPatientId.handler
    events:
      - httpApi:
          path: /patient/{patientId}
          method: GET
          cors: true

  findAllFoods:
    handler: src/server/functions/food/findAll.handler
    events:
      - httpApi:
          path: /foods
          method: GET
          cors: true

  findAllCategoryName:
    handler: src/server/functions/categoryName/findAll.handler
    events:
      - httpApi:
          path: /categoryName
          method: GET
          cors: true

  createPlanningMeal:
    handler: src/server/functions/planningMeal/create.handler
    events:
      - httpApi:
          path: /planningMeal/{patientId}
          method: POST
          cors: true
  findAllPlanning:
    handler: src/server/functions/planningMeal/findAll.handler
    events:
      - httpApi:
          path: /planningMeal/{patientId}
          method: GET
          cors: true

  createAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/create.handler
    events:
      - httpApi:
          path: /anamnesisTemplate
          method: POST
          cors: true
  findAllAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/findAll.handler
    events:
      - httpApi:
          path: /anamnesisTemplate
          method: GET
          cors: true
  deleteAnamnesisTemplate:
    handler: src/server/functions/anamnesisTemplate/delete.handler
    events:
      - httpApi:
          path: /anamnesisTemplate/{anamnesisId}
          method: DELETE
          cors: true

  createAnamnesis:
    handler: src/server/functions/anamnesis/create.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: POST
          cors: true
  findAllAnamnesis:
    handler: src/server/functions/anamnesis/findAll.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: GET
          cors: true
  updateAnamnesis:
    handler: src/server/functions/anamnesis/update.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}
          method: PUT
          cors: true
  deleteAnamnesis:
    handler: src/server/functions/anamnesis/delete.handler
    events:
      - httpApi:
          path: /anamnesis/{patientId}/{anamnesisId}
          method: DELETE
          cors: true

  userMe:
    handler: src/server/functions/user/me.handler
    events:
      - httpApi:
          path: /user/me
          method: GET
          cors: true
